-- MySQL Workbench Synchronization
-- Generated: 2018-01-31 09:53
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Michal Juhas

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `db_design_1`.`ref_order_status` 
ADD COLUMN `description` VARCHAR(300) NULL DEFAULT NULL AFTER `name`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
